---
- name: Setup conf file
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    insertafter: EOF
    line: "{{ item }}"
    create: yes
    loop: "{{ modules }}"

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernelModules }}"

- name: Setup sysctl params
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    insertafter: EOF
    line: "{{ item }}"
    create: yes
    loop: "{{ sysctlParams }}"

- name: Install containerd.io
  include_tasks: pkg.yml

- name: Create a containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: creating default config
  shell: containerd config default > /etc/containerd/config.toml

- name: Restart service containerd
  service:
    name: containerd.io
    state: restarted

